
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class Addbus extends javax.swing.JInternalFrame {

    /**
     * Creates new form Addbus
     */
    public Addbus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tn = new javax.swing.JTextField();
        ts = new javax.swing.JTextField();
        td = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tna = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tdd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Train Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("train no");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Source");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Destination");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        tn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnActionPerformed(evt);
            }
        });
        getContentPane().add(tn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 207, -1));
        getContentPane().add(ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 207, -1));
        getContentPane().add(td, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 207, 26));

        jButton1.setBackground(new java.awt.Color(153, 255, 102));
        jButton1.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));
        getContentPane().add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 200, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 51, -1));

        tna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnaActionPerformed(evt);
            }
        });
        getContentPane().add(tna, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 200, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 57, -1));

        tdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tddActionPerformed(evt);
            }
        });
        getContentPane().add(tdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 200, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pexels-alexander-grey-1191710.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-13, -226, 6150, 4220));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void clear(){
       tn.setText("");
           ts.setText("");
        td.setText("");
           
}
PreparedStatement pst;
Date date;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:

            
            // TODO add your handling c/ode here:
            String no=tn.getText();
           String date=tdd.getText();
          
            String start=ts.getText();
            String destination=td.getText();
            String price=tp.getText();
            String name=tna.getText();
            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
            
                
                      PreparedStatement pst =con.prepareStatement("insert into td(no,name,start,destination,price,date)values(?,?,?,?,?,?)");
               
                pst.setString(1,no);
                pst.setString(2,name);
                
                pst.setString(3,start);
                pst.setString(4,destination);
                pst.setString(5,price);
                
                pst.setString(6,date);
                
             int k= pst.executeUpdate(); 
             if(k==1){
                 JOptionPane.showMessageDialog(this, "added");
             }else{
                JOptionPane.showMessageDialog(this, " not added");
                 
             }
             tn.setText("");
            ts.setText("");
            td.setText("");
            tp.setText("");
            tna.setText("");  
            
            tdd.setText("");  
            tn.requestFocus();
            
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.setVisible(false);
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnActionPerformed

    private void tddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tddActionPerformed

    private void tnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField td;
    private javax.swing.JTextField tdd;
    private javax.swing.JTextField tn;
    private javax.swing.JTextField tna;
    private javax.swing.JTextField tp;
    private javax.swing.JTextField ts;
    // End of variables declaration//GEN-END:variables
}
