/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
import java.awt.event.*;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class addbooking extends javax.swing.JInternalFrame {

    /**
     * Creates new form addbooking
     */
    public addbooking() {
        initComponents();
       loadstart();
       loaddes();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet r;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tb = new javax.swing.JTextField();
        tp = new javax.swing.JTextField();
        tt = new javax.swing.JTextField();
        tpp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tse = new javax.swing.JTextField();
        tot = new javax.swing.JTextField();
        jc = new javax.swing.JComboBox<>();
        jce = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tdd = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("train no");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Start");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Des");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 257, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("pno");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 265, -1, -1));
        getContentPane().add(tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 74, 128, -1));
        getContentPane().add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 164, 125, -1));

        tt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttActionPerformed(evt);
            }
        });
        getContentPane().add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 261, 125, -1));
        getContentPane().add(tpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 261, 135, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("seats");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 358, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("total");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 358, -1, -1));

        tse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tseKeyPressed(evt);
            }
        });
        getContentPane().add(tse, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 362, 135, -1));
        getContentPane().add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 362, 135, -1));

        jc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(jc, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 74, 128, -1));

        getContentPane().add(jce, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 164, 131, -1));

        jButton2.setBackground(new java.awt.Color(212, 71, 214));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 204));
        jButton2.setText("Reserve");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 428, -1, -1));

        jButton3.setBackground(new java.awt.Color(213, 57, 227));
        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 204));
        jButton3.setText("cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 432, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 428, -1, -1));
        getContentPane().add(tdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 428, 135, -1));

        jButton4.setBackground(new java.awt.Color(222, 135, 221));
        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 204));
        jButton4.setText("search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1004, 67, -1, -1));

        jPanel1.setBackground(new java.awt.Color(246, 185, 195));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setText("ADD BOOKING DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1781535.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -240, 1680, 1280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadstart(){
        
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
            
            PreparedStatement ps1=con.prepareStatement("SELECT start FROM td");
            r= ps1.executeQuery();
            jc.removeAllItems();
            while(r.next()){
                jc.addItem(r.getString(1));
            }
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, ex);
        }
    
    }

    public void loaddes(){
        
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
            
            PreparedStatement ps1=con.prepareStatement("SELECT destination FROM td");
            r= ps1.executeQuery();
            jce.removeAllItems();
            while(r.next()){
                jce.addItem(r.getString(1));
            }
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, ex);
        }
    
    }
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            
           
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handli
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            
            // TODO add your handling c/ode here:
            String tno=tb.getText();
           String date=tdd.getText();
           String pno=tpp.getText();
            String start=jc.getSelectedItem().toString();
            String destination=jce.getSelectedItem().toString();
            String price=tp.getText();
            String seat=tse.getText();
            String tname=tt.getText();
            String total=tot.getText();
            
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
            
                
                      PreparedStatement pst =con.prepareStatement("insert into pd(pno,tno,tname,start,destination,price,date,seat,total)values(?,?,?,?,?,?,?,?,?)");
               
                pst.setString(1,pno);
                pst.setString(2,tno);
                
                pst.setString(3,tname);
                pst.setString(4,start);
                pst.setString(5,destination);
                pst.setString(6,price);
                  pst.setString(7,date);
                  pst.setString(8,seat);
                  
                pst.setString(9,total);
                
             int k= pst.executeUpdate(); 
             if(k==1){
                 JOptionPane.showMessageDialog(this, "added");
             }else{
                JOptionPane.showMessageDialog(this, " not added");
                 
             }
             clear();
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void clear(){
        tb.setText("");
        
        tdd.setText("");
        tse.setText("");
        tp.setText("");
        tt.setText("");
        tot.setText("");
        tpp.setText("");
    
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            String s=jc.getSelectedItem().toString();
            String d=jce.getSelectedItem().toString();
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
            
            PreparedStatement ps2=con.prepareStatement("SELECT * FROM td where start=? and destination=?");
            ps2.setString(1, s);
            ps2.setString(2, d);
            r= ps2.executeQuery();
            if(r.next()==true){
                tb.setText(r.getString(2));
                tp.setText(r.getString(6));
                tt.setText(r.getString(3));
                tdd.setText(r.getString(7));
                     
            }
            else{
                    JOptionPane.showMessageDialog(this, "not found");
                
            }
        } catch (SQLException ex) {
            
         JOptionPane.showMessageDialog(this, ex);
       
        }
            
           
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttActionPerformed

    private void tseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tseKeyPressed
        // TODO add your handling code here:
        int p,t,to;
        if(evt.getKeyCode()==  KeyEvent.VK_ENTER){
            p=Integer.parseInt(tp.getText());
            t=Integer.parseInt(tse.getText());
            to=p*t;
            tot.setText(String.valueOf(to));
        }
    }//GEN-LAST:event_tseKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jc;
    private javax.swing.JComboBox<String> jce;
    private javax.swing.JTextField tb;
    private javax.swing.JTextField tdd;
    private javax.swing.JTextField tot;
    private javax.swing.JTextField tp;
    private javax.swing.JTextField tpp;
    private javax.swing.JTextField tse;
    private javax.swing.JTextField tt;
    // End of variables declaration//GEN-END:variables
}
