import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class delete extends javax.swing.JInternalFrame {

    /**
     * Creates new form delete
     */
    public delete() {
        
        initComponents();
        train();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tb = new javax.swing.JTextField();
        tna = new javax.swing.JTextField();
        ts = new javax.swing.JTextField();
        td = new javax.swing.JTextField();
        tp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tdd = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("DELETE TRAIN DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("tno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 71, 33, -1));
        getContentPane().add(tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 101, -1));

        tna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnaActionPerformed(evt);
            }
        });
        getContentPane().add(tna, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 119, 101, -1));

        ts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsActionPerformed(evt);
            }
        });
        getContentPane().add(ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 163, 101, -1));
        getContentPane().add(td, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 207, 101, -1));

        tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpActionPerformed(evt);
            }
        });
        getContentPane().add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 251, 101, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 115, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("start");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 159, 47, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("dest");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 203, 47, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 247, 47, -1));

        jTable1.setBackground(new java.awt.Color(241, 226, 226));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "no", "name", "start", "destination", "price", "date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 714, 231));

        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 372, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 308, 47, -1));

        tdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tddActionPerformed(evt);
            }
        });
        getContentPane().add(tdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 312, 101, -1));

        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 372, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -390, 2790, 1450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnaActionPerformed

    private void tsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsActionPerformed

    private void tpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpActionPerformed
ResultSet r;
PreparedStatement ps;
    public void train(){
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
        
            ps=con.prepareStatement("select * from td");
            r=ps.executeQuery();
            ResultSetMetaData rs=r.getMetaData();
            int c=rs.getColumnCount();
            
            
             DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
             d.setRowCount(0);
             while(r.next()){
                 Vector v=new Vector();
                 for(int i=0;i<=c;i++){
                     
                     
                     v.add(r.getString("no"));
                     v.add(r.getString("name"));
                     v.add(r.getString("start"));
                     v.add(r.getString("destination"));
                     v.add(r.getString("price"));
                     v.add(r.getString("date"));
                           
                 }
                d.addRow(v);
             }
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex);
        }
                     
        
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        try {
            // TODO add your handling code here:
            
            // TODO add your handling c/ode here:
            String no=tb.getText();
         
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
             PreparedStatement pst =con.prepareStatement("delete from td where no=?");
                pst.setString(1,no);
                int k=pst.executeUpdate();
            
            if(k==1){
            JOptionPane.showMessageDialog(this, "deleted");
            }else{
            JOptionPane.showMessageDialog(this, " not updated");
                
            }
            tb.setText("");
            ts.setText("");
            td.setText("");
            tp.setText("");
            tna.setText("");  
            
            tdd.setText("");  
            tb.requestFocus();
            train();
            
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(this, ex);
              
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
            DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
       int s=jTable1.getSelectedRow();
       tb.setText(d.getValueAt(s, 0).toString()); 
       tna.setText(d.getValueAt(s, 1).toString());
       
       ts.setText(d.getValueAt(s, 2).toString());
       td.setText(d.getValueAt(s, 3).toString());
       tp.setText(d.getValueAt(s, 4).toString());
       
       tdd.setText(d.getValueAt(s, 5).toString());
       
       
       
       
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void tddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.setVisible(false);
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tb;
    private javax.swing.JTextField td;
    private javax.swing.JTextField tdd;
    private javax.swing.JTextField tna;
    private javax.swing.JTextField tp;
    private javax.swing.JTextField ts;
    // End of variables declaration//GEN-END:variables
}
