
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class deletebooking extends javax.swing.JInternalFrame {

    /**
     * Creates new form deletebooking
     */
    public deletebooking() {
        initComponents();
        train();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tn = new javax.swing.JTextField();
        na = new javax.swing.JTextField();
        ts = new javax.swing.JTextField();
        td = new javax.swing.JTextField();
        tp = new javax.swing.JTextField();
        tse = new javax.swing.JTextField();
        tot = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tdd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 102));
        jLabel1.setText("pno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 77, 55, -1));
        getContentPane().add(tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 81, 193, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("tno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 133, 55, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("tname");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, 55, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("start");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, 55, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("dest");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 326, 55, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 394, 55, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 153));
        jLabel7.setText("seats");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 515, 55, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("total");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 578, 55, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 153));
        jLabel9.setText("date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 453, 55, -1));
        getContentPane().add(tn, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 137, 193, -1));

        na.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naActionPerformed(evt);
            }
        });
        getContentPane().add(na, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 190, 196, -1));

        ts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsActionPerformed(evt);
            }
        });
        getContentPane().add(ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 254, 202, -1));
        getContentPane().add(td, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 205, -1));
        getContentPane().add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 398, 202, -1));
        getContentPane().add(tse, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 515, 208, -1));
        getContentPane().add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 578, 202, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "pno", "tno", "tname", "start", "destination", "price", "date", "seats", "total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 710, 228));

        tdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tddActionPerformed(evt);
            }
        });
        getContentPane().add(tdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 453, 202, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("DELETE BOOKING DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newimage/pf-s80-pastel-ploy-01a_1.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -10, 1120, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsActionPerformed
ResultSet r;
PreparedStatement ps;
    
    public void train(){
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
        
            ps=con.prepareStatement("select * from pd");
            r=ps.executeQuery();
            ResultSetMetaData rs=r.getMetaData();
            int c=rs.getColumnCount();
            
            
             DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
             d.setRowCount(0);
             while(r.next()){
                 Vector v=new Vector();
                 for(int i=0;i<=c;i++){
                     
                     v.add(r.getString("pno"));
                     
                     v.add(r.getString("tno"));
                     
                     v.add(r.getString("tname"));
                     v.add(r.getString("start"));
                     v.add(r.getString("destination"));
                     v.add(r.getString("price"));
                     v.add(r.getString("date"));
                      v.add(r.getString("seat"));
                     v.add(r.getString("total"));
                                          
                     
                 }
                d.addRow(v);
             }
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex);
        }
                     
        
    }


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
   DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
       int s=jTable1.getSelectedRow();
       tb.setText(d.getValueAt(s, 0).toString()); 
       tn.setText(d.getValueAt(s, 1).toString());
       na.setText(d.getValueAt(s, 2).toString());
       
       ts.setText(d.getValueAt(s, 3).toString());
       td.setText(d.getValueAt(s, 4).toString());
       tp.setText(d.getValueAt(s, 5).toString());
       tdd.setText(d.getValueAt(s, 6).toString());
           tse.setText(d.getValueAt(s, 7).toString());
         tot.setText(d.getValueAt(s, 8).toString());
                 // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            // TODO add your handling code here:
            
            // TODO add your handling c/ode here:
           
            String tno=tn.getText();
            
         
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
             PreparedStatement pst =con.prepareStatement("delete from pd where tno=?");
                pst.setString(1,tno);
            int k=   pst.executeUpdate();
            
            if(k==1){
            JOptionPane.showMessageDialog(this, "deleted");
            }else{
            JOptionPane.showMessageDialog(this, " not deleted");
                
            }
            
            
            tb.setText("");
            tn.setText("");
            ts.setText("");
            td.setText("");
            tp.setText("");
            na.setText("");  
            
            tse.setText(""); 
            tdd.setText(""); 
            tot.setText(""); 
            tn.setText(""); 
            tn.requestFocus();
            train();
            
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(this, ex);
              
        }
                
               
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.setVisible(false);
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tddActionPerformed

    private void naActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField na;
    private javax.swing.JTextField tb;
    private javax.swing.JTextField td;
    private javax.swing.JTextField tdd;
    private javax.swing.JTextField tn;
    private javax.swing.JTextField tot;
    private javax.swing.JTextField tp;
    private javax.swing.JTextField ts;
    private javax.swing.JTextField tse;
    // End of variables declaration//GEN-END:variables
}
