import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class editbooking extends javax.swing.JInternalFrame {

    /**
     * Creates new form editbooking
     */
    public editbooking() {
        initComponents();
    train();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tb = new javax.swing.JTextField();
        tn = new javax.swing.JTextField();
        na = new javax.swing.JTextField();
        ts = new javax.swing.JTextField();
        td = new javax.swing.JTextField();
        tp = new javax.swing.JTextField();
        tdd = new javax.swing.JTextField();
        tse = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("pno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("start");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 178, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("des");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 228, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 282, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 332, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("total");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 461, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("tname");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 128, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("tno");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 78, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("pno");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 160, 0, -1));
        getContentPane().add(tb, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 32, 110, -1));
        getContentPane().add(tn, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 82, 110, -1));
        getContentPane().add(na, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 132, 110, -1));
        getContentPane().add(ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 182, 104, -1));
        getContentPane().add(td, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 232, 104, -1));
        getContentPane().add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 282, 110, -1));

        tdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tddActionPerformed(evt);
            }
        });
        getContentPane().add(tdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 332, 110, -1));
        getContentPane().add(tse, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 401, 110, -1));
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 465, 110, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("seat");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 401, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "pno", "tno", "tname", "start", "destination", "price", "date", "seat", "total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 570, 312));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel11.setText("EDIT BOOKING DETAILS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newimage/p4.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -290, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

      this.setVisible(false);
   

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
               DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
       int s=jTable1.getSelectedRow();
       tb.setText(d.getValueAt(s, 0).toString()); 
       tn.setText(d.getValueAt(s, 1).toString());
       na.setText(d.getValueAt(s, 2).toString());
       
       ts.setText(d.getValueAt(s, 3).toString());
       td.setText(d.getValueAt(s, 4).toString());
       tp.setText(d.getValueAt(s, 5).toString());
       tdd.setText(d.getValueAt(s, 6).toString());
           tse.setText(d.getValueAt(s, 7).toString());
         to.setText(d.getValueAt(s, 8).toString());
         
            
       
       
    }//GEN-LAST:event_jTable1MouseClicked
ResultSet r;
PreparedStatement ps;
    
    public void train(){
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
        
            ps=con.prepareStatement("select * from pd");
            r=ps.executeQuery();
            ResultSetMetaData rs=r.getMetaData();
            int c=rs.getColumnCount();
            
            
             DefaultTableModel d=(DefaultTableModel)jTable1.getModel();
             d.setRowCount(0);
             while(r.next()){
                 Vector v=new Vector();
                 for(int i=0;i<=c;i++){
                     
                     v.add(r.getString("pno"));
                     
                     v.add(r.getString("tno"));
                     
                     v.add(r.getString("tname"));
                     v.add(r.getString("start"));
                     v.add(r.getString("destination"));
                     v.add(r.getString("price"));
                     v.add(r.getString("date"));
                      v.add(r.getString("seat"));
                     v.add(r.getString("total"));
                                          
                     
                 }
                d.addRow(v);
             }
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex);
        }
                     
        
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            
            // TODO add your handling c/ode here:
            String pno=tb.getText();
            String tno=tn.getText();
            String start=ts.getText();
            String destination=td.getText();
            
            String date=tdd.getText();
            String price=tp.getText();
            String seat=tse.getText();
            String total=to.getText();
            String tname=na.getText();
            
            
         
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/newuser","root","");
             PreparedStatement pst =con.prepareStatement("update pd set pno=?,tname=?,start=?,destination=?,price=?,date=?,seat=?,total=? where tno=?");
                pst.setString(1,pno);
                pst.setString(2,tname);
                pst.setString(3,start);
                
                pst.setString(4,destination);
                pst.setString(5,price);
                  pst.setString(6,date);
                    pst.setString(7,seat);
                      pst.setString(8,total);
                pst.setString(9,tno);
            int k=   pst.executeUpdate();
            
            if(k==1){
            JOptionPane.showMessageDialog(this, "updated");
            }else{
            JOptionPane.showMessageDialog(this, " not updated");
                
            }
            tb.setText("");
            ts.setText("");
            td.setText("");
            tp.setText("");
            na.setText("");  
            
            tse.setText(""); 
            tdd.setText(""); 
            to.setText(""); 
            tn.setText(""); 
            tb.requestFocus();
            train();
            
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(this, ex);
              
        }
                
               
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField na;
    private javax.swing.JTextField tb;
    private javax.swing.JTextField td;
    private javax.swing.JTextField tdd;
    private javax.swing.JTextField tn;
    private javax.swing.JTextField to;
    private javax.swing.JTextField tp;
    private javax.swing.JTextField ts;
    private javax.swing.JTextField tse;
    // End of variables declaration//GEN-END:variables
}
